# coding: utf-8

"""
    FlashBlade REST API

    OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

    The version of the OpenAPI document: 2.28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Set, Dict, Any

from typing import List, Optional

try:
    from pydantic.v1 import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
except ModuleNotFoundError:
    from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
from pypureclient.flashblade._common.models.fixed_reference_v_2_22 import FixedReference


class Audit(BaseModel):
    """
    Audit
    """
    id: Optional[StrictStr] = Field(default=None, description="A non-modifiable, globally unique ID chosen by the system.")
    name: Optional[StrictStr] = Field(default=None, description="Name of the object (e.g., a file system or snapshot).")
    context: Optional[FixedReference] = Field(default=None, description="The context in which the operation was performed. Valid values include a reference to any array which is a member of the same fleet or to the fleet itself. Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided `context`.")
    arguments: Optional[StrictStr] = None
    command: Optional[StrictStr] = None
    correlation_id: Optional[StrictStr] = Field(default=None, description="A unique identifier that connects user-triggered system actions to the user action that caused them. User actions that do not trigger other actions will not have a correlation ID.")
    ip_address: Optional[StrictStr] = None
    origin: Optional[FixedReference] = None
    scopes: Optional[conlist(FixedReference)] = Field(default=None, description="The realms and/or array which this audit affected and is visible to.")
    subcommand: Optional[StrictStr] = None
    system_event: Optional[StrictBool] = Field(default=None, description="If true, then this audit record represents a system-initiated event. If false, it represents an event invoked directly by a user.")
    time: Optional[StrictInt] = None
    user: Optional[StrictStr] = None
    user_agent: Optional[StrictStr] = None
    user_interface: Optional[StrictStr] = Field(default=None, description="The user interface through which the user session event was performed. Valid values are `CLI`, `GUI`, and `REST`.")
    __properties = ["id", "name", "context", "arguments", "command", "correlation_id", "ip_address", "origin", "scopes", "subcommand", "system_event", "time", "user", "user_agent", "user_interface"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.to_dict(include_readonly=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.as_request_dict())

    def as_request_dict(self) -> Dict[str, Any]:
        return self.to_dict(include_readonly=False)

    def to_dict(self, include_readonly: bool=True) -> Dict[str, Any]:

        """Returns the dictionary representation of the model using alias"""
        excluded_fields: Set[str] = set()
        if not include_readonly:
            excluded_fields.update([
                "id",
                "name",
                "context",
                "arguments",
                "command",
                "correlation_id",
                "ip_address",
                "subcommand",
                "system_event",
                "time",
                "user",
                "user_agent",
                "user_interface",
            ])
        none_fields: Set[str] = set()
        for _field in self.__fields__.keys():
            if super().__getattribute__(_field) is None:
                none_fields.add(_field)

        _dict = self.dict(by_alias=True, exclude=excluded_fields, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of context
        if _include_in_dict('context', include_readonly, excluded_fields, none_fields):
            _dict['context'] = self.context.to_dict(include_readonly=include_readonly)
        # override the default output from pydantic by calling `to_dict()` of origin
        if _include_in_dict('origin', include_readonly, excluded_fields, none_fields):
            _dict['origin'] = self.origin.to_dict(include_readonly=include_readonly)
        # override the default output from pydantic by calling `to_dict()` of each item in scopes (list)
        if _include_in_dict('scopes', include_readonly, excluded_fields, none_fields):
            _items = []
            for _item in self.scopes:
                if _item:
                    _items.append(_item.to_dict(include_readonly=include_readonly))
            _dict['scopes'] = _items
        return _dict

    def __getitem__(self, key):
        return super().__getattribute__(key)

    def __setitem__(self, key, value):
        setattr(self, key, value)

    def __delitem__(self, key):
        setattr(self, key, None)

    def __getattribute__(self, name: str) -> Any:
        _value = super().__getattribute__(name)
        if _value is None and name in self.__fields__.keys() and _should_raise_on_none():
            raise AttributeError
        return _value
    def __str__(self) -> str:
        return self.to_str()

    def __repr__(self) -> str:
        return self.to_str()

    @classmethod
    def from_json(cls, json_str: str) -> Audit:
        """Create an instance of Audit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    @classmethod
    def from_dict(cls, obj: dict) -> Audit:
        """Create an instance of Audit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Audit.parse_obj(obj)

        _obj = Audit.construct(_fields_set=None, **{
            "id": obj.get("id"),
            "name": obj.get("name"),
            "context": FixedReference.from_dict(obj.get("context")) if obj.get("context") is not None else None,
            "arguments": obj.get("arguments"),
            "command": obj.get("command"),
            "correlation_id": obj.get("correlation_id"),
            "ip_address": obj.get("ip_address"),
            "origin": FixedReference.from_dict(obj.get("origin")) if obj.get("origin") is not None else None,
            "scopes": [FixedReference.from_dict(_item) for _item in obj.get("scopes")] if obj.get("scopes") is not None else None,
            "subcommand": obj.get("subcommand"),
            "system_event": obj.get("system_event"),
            "time": obj.get("time"),
            "user": obj.get("user"),
            "user_agent": obj.get("user_agent"),
            "user_interface": obj.get("user_interface")
        })
        return _obj

def _should_raise_on_none() -> bool:
    import importlib
    _package = importlib.import_module(__package__)
    return _package._attribute_error_on_none

def _include_in_dict(name: str, include_readonly: bool, excluded_fields: Set[str], none_fields: Set[str]) -> bool:
    if name in none_fields:
        return False
    return (include_readonly or name not in excluded_fields)

